version: "3"

services:
  api:
    image: arm64v8/cassandra:4.1
    container_name: local-cassandra-node-1
    restart: unless-stopped
    environment:
      CASSANDRA_CLUSTER_NAME: cu-freelance
      CASSANDRA_PASSWORD_SEEDER: "yes"
      CASSANDRA_PASSWORD: root
      CASSANDRA_SEEDS: local-cassandra-node-1
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - my-services
    ports:
      - "9042:9042"

  local-db:
    image: postgres:15.1-alpine3.17
    container_name: cu-freelance-local-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  local-cache:
    image: bitnami/redis:6.2.6
    container_name: cu-freelance-local-cache
    restart: unless-stopped
    environment:
      REDIS_HOST: localhost
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"

  rabbitmq-local:
    image: rabbitmq:3.9.26-management-alpine
    container_name: rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:1.42
    container_name: jaeger-local
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
