version: "3"

services:
  api:
    image: ghcr.io/miello/cloud-final-api:latest
    container_name: jerm-resume-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:8000"
      - "443:8000"
